USE express_crud_db;

CREATE TABLE IF NOT EXISTS admins (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  name VARCHAR(150) NOT NULL,
  address VARCHAR(255),
  email VARCHAR(150) UNIQUE,
  phone VARCHAR(20),
  role VARCHAR(50) DEFAULT 'admin',
  token CHAR(36) NOT NULL UNIQUE DEFAULT (UUID()), -- 36-char unique token
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
