USE express_crud_db;
ALTER TABLE instances
  ADD COLUMN IF NOT EXISTS uuid CHAR(36) UNIQUE DEFAULT (UUID());
ALTER TABLE instances
  ADD COLUMN IF NOT EXISTS webhook_url VARCHAR(500) DEFAULT NULL;
UPDATE instances SET uuid = UUID() WHERE uuid IS NULL;
